---
title: "GO/KEGG富集分析"
author: "陈同"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  html_document:
    df_print: paged
    theme: cerulean
    highlight: haddock
    toc: yes
    toc_depth: 3
    toc_float:
      collapsed: false
      smooth_scroll: true
    code_fold: show
---


```{r, echo=F}
knitr::opts_chunk$set( echo = TRUE, message=FALSE, warning=FALSE, fig.width=8 )
```

## 检查有无缺失的包并安装，加载所有包

```{r}
site = "https://mirrors.tuna.tsinghua.edu.cn/CRAN"

if (!requireNamespace("BiocManager", quietly = TRUE))
  install.packages("BiocManager", repos = site)

a = rownames(installed.packages())

# install.packages("tidyverse")

options(BioC_mirror="https://mirrors.tuna.tsinghua.edu.cn/bioconductor")

install_bioc <- c("tidyverse", "RColorBrewer", "ggplot2", "org.Hs.eg.db",
                  "reshape2", "stringr", "clusterProfiler","tidyr","devtools", 
                  "fastmatch", "downloader", "ggraph", "aplot","ape", "tidytree",
                  "scatterpie", "shadowtext", "conflicted")

for (i in install_bioc) {
  if (!i %in% a){
    BiocManager::install(i, update = F, site_repository=site)
    a = rownames(installed.packages())
  }
    
}

# BiocManager::install("YuLab-SMU/clusterProfiler", update = F)

if (!"ImageGP" %in% a){
  # devtools::install_github("Tong-Chen/ImageGP")
  devtools::install_git("https://gitee.com/ct5869/ImageGP.git")
}
```

### Gene ID转换

不同软件识别的ID不同，需要做相应的转换。

```{r}
suppressMessages(library(tidyverse))
suppressMessages(library(ImageGP))

idmap <- read.table("13_salmon_deseq2/genome/GRCh38.idmap.txt", sep="\t", header=T, row.names=NULL, quote="")

all_DE <- read.table("result/salmon_deseq2/ehbio.simplier.DESeq2.all.DE.txt", sep="\t", header=F, row.names=NULL, quote="")

combine_de <- left_join(all_DE, idmap, by=c("V1"="ENSG"))

all_entrez <- combine_de[,c(4,2)]

write.table(all_entrez[all_entrez[,1] != "",,drop=F], file="result/salmon_deseq2/ehbio.DESeq2.all.DE.entrez.txt", quote=F, sep="\t", row.names=F, col.names=F)

all_symbol <- combine_de[,c(3,2)]
write.table(all_symbol[all_symbol[,1] !="", ,drop=F], file="result/salmon_deseq2/ehbio.DESeq2.all.DE.symbol.txt", quote=F, sep="\t", row.names=F, col.names=F)
```



### KEGG富集分析

富集分析需要这两个输入参数（跟GO相同），注意根据需要修改。

```{r init_go_kegg}
de_file <- "15_enrichment/ehbio.DESeq2.all.DE.entrez.txt"
# 查找orgDB信息和名字
# https://www.bioconductor.org/packages/release/BiocViews.html#___OrgDb
org_db <- "org.Hs.eg.db"
library(ImageGP)
library(stringr)
library(fastmatch)
library(clusterProfiler)

dir.create("result/GOKEGG_enrichment")

# 如果遇到报错 Error in down1oad. KEGG.Path(species) :
# 'species' should be one of organisms 1isted in 'http://omww.genome. jp/kegg/catalog/org_lIist. htm)'. ..cal1s: <Anonymous> ... prepare_KEGG -> download_KEGG -> download.KEGG.Path
# 运行下面的代码重新安装clusterProfiler；如果安装不了，关闭Rstudio，再次打开后，先运行
# 下面的代码安装包，再操作其它代码
# BiocManager::install("clusterProfiler", update = F, site_repository=site)
# 
all_result <- enrichKEGG_model(de_file, org_db=org_db, 
   output_prefix="result/GOKEGG_enrichment/ehbio.DESeq2.all.DE.entrez",
                 organism="hsa",
                 pvalueCutoff=0.05, qvalueCutoff=0.2,
                 setReadable=TRUE)

sp_enrichment("result/GOKEGG_enrichment/ehbio.DESeq2.all.DE.entrez.all.KEGG.xls", xvariable="GeneRatio",
              yvariable="Description", size_variable = "Count", color_variable = "qvalue",
              log10_transform_variable="qvalue",
              shape_variable = "Group")
```


#### 富集分析泡泡图绘制 (在线绘制 <http://www.ehbio.com/ImageGP>)

http://www.ehbio.com/Cloud_Platform/front/#/

https://www.bic.ac.cn/BIC

### GO富集分析R代码


富集分析需要这两个输入参数（差异基因列表和注释数据库），注意根据需要修改。

```{r init_go_kegg2, eval=T}
library(ImageGP)
library(stringr)
library(conflicted)
library(clusterProfiler)

conflict_prefer("simplify", "clusterProfiler")

de_file <- "15_enrichment/ehbio.DESeq2.all.DE.entrez.txt"
org_db <- "org.Hs.eg.db"
# 因基因数目较多，运行需要至少3G内存，15分钟左右时间，系统可能卡死。
all_result <- enrichGO_model(de_file, org_db=org_db, 
                 output_prefix="result/GOKEGG_enrichment/ehbio.DESeq2.all.DE.entrez",
                 pvalueCutoff=0.05, qvalueCutoff=0.2,
                 setReadable=TRUE, typeL = c("CC", "BP"))

sp_enrichment("result/GOKEGG_enrichment/ehbio.DESeq2.all.DE.entrez.CC.all.xls", xvariable="GeneRatio",
              yvariable="Description", size_variable = "Count", color_variable = "qvalue",
              shape_variable = "Group")

# sp_enrichment("result/GOKEGG_enrichment/ehbio.DESeq2.all.DE.entrez.BP.all.xls", xvariable="GeneRatio",
#              yvariable="Description", size_variable = "Count", color_variable = "qvalue",
#              shape_variable = "Group")

# sp_enrichment("result/GOKEGG_enrichment/ehbio.DESeq2.all.DE.entrez.MF.all.xls", xvariable="GeneRatio",
#               yvariable="Description", size_variable = "Count", color_variable = "qvalue",
#               shape_variable = "Group")
```


输出如下 (后续KEGG富集分析输出结果与此类似，不再赘述)

```
# 中间R代码
ehbio.DESeq2.all.DE.entrez.clusterProfileGO.r

# untrt上调基因的BP、MF、CC富集结果
ehbio.DESeq2.all.DE.entrez.untrt._higherThan_.trt.BP_GO.xls
ehbio.DESeq2.all.DE.entrez.untrt._higherThan_.trt.CC_GO.xls
ehbio.DESeq2.all.DE.entrez.untrt._higherThan_.trt.MF_GO.xls

# trt上调基因的BP、MF、CC富集结果
ehbio.DESeq2.all.DE.entrez.untrt._lowerThan_.trt.BP_GO.xls
ehbio.DESeq2.all.DE.entrez.untrt._lowerThan_.trt.CC_GO.xls
ehbio.DESeq2.all.DE.entrez.untrt._lowerThan_.trt.MF_GO.xls

# 上调基因的富集结果和下调基因的富集结果的top10的合并文件
ehbio.DESeq2.all.DE.entrez.all.BP.top10.xls
ehbio.DESeq2.all.DE.entrez.all.CC.top10.xls
ehbio.DESeq2.all.DE.entrez.all.MF.top10.xls
```


### 自有注释数据用于分析

#### 数据准备

从<http://software.broadinstitute.org/gsea/msigdb/collections.jsp> 下载的HallMark基因集`h.all.v6.2.entrez.gmt`。


数据转成2列格式，第一列为通路，第二列为基因


```{r}
gmtfile <- "15_enrichment/h.all.v6.2.symbols.gmt"
con <- file(gmtfile, open="r")

gmt2go <- read.csv(text="ont,gene")

while (length(oneLine <- readLines(con, n = 1, warn = FALSE)) > 0) {
    myVector <- unlist(strsplit(oneLine, "\t"))
    pathway <- myVector[1]
    geneV <- myVector[-(1:2)]
    
    tmpDF <- data.frame(ont=pathway, gene=geneV)
    gmt2go <- rbind(gmt2go, tmpDF)
  } 

close(con)

sp_writeTable(gmt2go, file="15_enrichment/h.all.v6.2.symbols.gmt.forGO", keep_rownames = F)


head(gmt2go)
rbind(head(gmt2go), tail(gmt2go))
```

#### 自有注释数据用于分析

```{r}
library(ImageGP)
library(stringr)
library(clusterProfiler)
# 注意两个文件中基因的ID必须完全一致
de_file <- "15_enrichment/ehbio.DESeq2.all.DE.symbol"
anno_file <- "15_enrichment/h.all.v6.2.symbols.gmt.forGO"

all_result <- enrichCustomizedPathway(de_file, anno_file, 
                 output_prefix="result/GOKEGG_enrichment/ehbio.DESeq2.all.DE.symbol.hallmark",
                 pvalueCutoff=0.05, qvalueCutoff=0.05)

sp_enrichment("result/GOKEGG_enrichment/ehbio.DESeq2.all.DE.symbol.hallmark.all.enriched.xls",
              xvariable="GeneRatio",
              yvariable="Description", size_variable = "Count", color_variable = "qvalue",
              shape_variable = "Group")
```


#### 富集分析泡泡图绘制 (在线绘制 <http://www.ehbio.com/ImageGP>)


## 富集分析结果导入Cytoscape进行网络展示


生成网络文件：通路-对应基因



```{r}
# $1表示第1列，通路名字
# $8表示第8列，通路中基因名字
# 请根据需要修改

# 生成网络文件
library(tidyr)
enrichFile <- "result/GOKEGG_enrichment/ehbio.DESeq2.all.DE.symbol.hallmark.all.enriched.xls"
enrichTable <- sp_readTable(enrichFile)[c(1,8)]

head(enrichTable)

netData <- separate_rows(enrichTable, geneID,sep="/")
colnames(netData) <- c("Source", "Target")
sp_writeTable(netData, file="result/GOKEGG_enrichment/ehbio.DESeq2.all.DE.symbol.Hallmark.xls.network.txt", keep_rownames = F)

head(netData)
```

生成属性文件：通路和基因

```{r}
## 生成属性文件
attributDF <- rbind(data.frame(ID=unique(netData$Source), class="Pathway"),
                    data.frame(ID=unique(netData$Target), class="Gene"))

sp_writeTable(attributDF, file="result/GOKEGG_enrichment/ehbio.DESeq2.all.DE.symbol.Hallmark.xls.table.txt", keep_rownames = F)

head(attributDF)
```

```{bash}
# awk 'BEGIN{OFS=FS="\t"}{gmt[$5"\t"$6]=gmt[$5"\t"$6]==""?$1:gmt[$5"\t"$6]"\t"$1}END{for(i in gmt) print i,gmt[i]}' 16_GSEA/timeseries/ATH_GO_GOSLIM.txt >16_GSEA/timeseries/ATH_GO_GOSLIM.txt.gmt 

```
